brainstrom/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (TopicListView,TopicDetailView,create_topic_form,
                    IdeaListView,IdeaDetailView,search,create_idea_form,
                    more_ideas_formset,topic_idea_render_pdf,TopicListViewNew,more_ideas,
                    IdeaListViewNew)

urlpatterns = [
    path('topiclist/',TopicListView.as_view(),name='topic_list'),
    path ('', TemplateView.as_view(template_name = 'home.html'), name='home'),
    path('topicdetail/<int:pk>',TopicDetailView.as_view(),name='topic_detail'),
    path('topicform/', create_topic_form, name='topic_form'),
    path('ideaform/',create_idea_form,name='idea_form'),
    path('idealist/',IdeaListView.as_view(),name='idea_list'),
    path('ideadetail/<int:pk>',IdeaDetailView.as_view(),name='idea_detail'),
    path('search/',search,name='search'),
    path('<int:topicname_id>/',more_ideas_formset,name='more_ideas'),
    path('more/<int:topicname_id>/',more_ideas,name='create_form'),
    path('meaningfull/',TemplateView.as_view(template_name='meaningfull.html'),name='enter_meaning'),
    path('pdf_format/<int:pk>',topic_idea_render_pdf,name='pdf_format'),
    path('topiclist_new/',TopicListViewNew.as_view(),name='topiclist_new'),
    path('idealist_new/',IdeaListViewNew.as_view(),name='idealist_new'),
]

evaluation/urls.py
from django.urls import path
from .views import (create_eval_form,EvalListView,more_pros_cons,EvalDetailView,eval_pros_cons_render_pdf,
                    search_eval)

urlpatterns = [
    path('evallist/', EvalListView.as_view(), name='eval_list'),
    path('evalform/', create_eval_form, name='eval_form'),
    path('evaldetail/<int:pk>',EvalDetailView.as_view(),name='eval_detail'),
    path('pros_cons/<int:question_id>/',more_pros_cons,name='more_pros_cons'),
    path('pdf_format/<int:pk>',eval_pros_cons_render_pdf,name='pdf_format_eval'),
    path('search_eval/',search_eval,name='search_eval'),
]

ideaboard_home/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('brainstrom.urls')),
    path('eval/',include('evaluation.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

evaluation/models.py
from django.db import models

from django.db import models

class EvaluationQModel(models.Model):
    question = models.CharField(max_length=100)

    class Meta:
        ordering = ['question']

    def __str__(self):
        return self.question

class ProsModel(models.Model):
    pros = models.TextField(blank=True, null=True)
    evaluation = models.ForeignKey(EvaluationQModel, on_delete=models.CASCADE)

    class Meta:
        ordering = ['pros']

    def __str__(self):
        return self.pros

class ConsModel(models.Model):
    cons = models.TextField(blank=True, null=True)
    evaluation = models.ForeignKey(EvaluationQModel, on_delete=models.CASCADE)

    class Meta:
        ordering = ['cons']

    def __str__(self):
        return self.cons

evaluation/forms.py
from django import forms
from django.forms import BaseModelFormSet
from .models import EvaluationQModel
from django.core.exceptions import ValidationError

class EvaluationQForm(forms.ModelForm):
    class Meta:
        model = EvaluationQModel
        fields = ['question']

    def clean(self):
        super(EvaluationQForm, self).clean()
        try:
            question = self.cleaned_data.get('question')
            EvaluationQModel.objects.get(question__icontains=question)
            raise forms.ValidationError('Question Already exists!')
        except EvaluationQModel.DoesNotExist:
            return self.cleaned_data

class BaseProsFormset(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.queryset = ProsModel.objects.none()

    def clean(self):
        super(BaseProsFormset, self).clean()
        if any(self.errors):
            return
        pross = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            pros = form.cleaned_data.get('pros')
            if pros in pross:
                raise ValidationError("Pros already given.")
            pross.append(pros)

class BaseConsFormset(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.queryset = ConsModel.objects.none()

    def clean(self):
        super(BaseConsFormset, self).clean()
        if any(self.errors):
            return
        conss = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            cons = form.cleaned_data.get('cons')
            if cons in conss:
                raise ValidationError("cons already given.")
            conss.append(cons)

evaluation/views.py
from django.shortcuts import render,HttpResponseRedirect,reverse,redirect,get_object_or_404
from .forms import EvaluationQForm,BaseProsFormset,BaseConsFormset
from .models import EvaluationQModel,ProsModel,ConsModel
from django.forms import modelformset_factory
from django.views.generic import ListView,DetailView
from django.contrib import messages
from django.http import HttpResponse
from xhtml2pdf import pisa
from django.template.loader import get_template

# creating a evaluation form
def create_eval_form(request):
    if request.method == 'POST':
        form = EvaluationQForm(request.POST)
        if form.is_valid():
            form.save()
            eval = form.save()
            #return redirect('eval_list')
            return HttpResponseRedirect(reverse('eval_detail',args=(eval.pk,)))
    else:
        form = EvaluationQForm()
    return render(request, 'create_evaluation_form.html', {'form': form})

#this is the generic class 'evaluation list' view
class EvalListView(ListView):
    model = EvaluationQModel
    template_name = 'eval_list.html'
    context_object_name = 'evals'
    ordering = ['question']
    paginate_by = 1

#this is the generic class 'topic detail' view
class EvalDetailView(DetailView):
    model = EvaluationQModel
    template_name = 'eval_detail.html'
    context_object_name = 'eval'

#this is the general evaluation search function.
def search_eval(request):
    query = request.GET.get('q')
    template = 'search_eval.html'
    start_flag = 0
    if query:
        query_pros = ProsModel.objects.filter(evaluation__question__contains=query)
        query_cons = ConsModel.objects.filter(evaluation__question__contains=query)
        if query_pros or query_cons:
            eval_name = EvaluationQModel.objects.get(question__icontains=query)
            context = {'pros':query_pros,'cons':query_cons,'eval_name':eval_name}
            return render(request, template, context)
        else:
            start_flag=1
            return render(request, template, {'start_flag': start_flag})

    return render(request,template,{'start_flag':start_flag})


def more_pros_cons(request,question_id):
    eval_name = EvaluationQModel.objects.get(pk=question_id)
    ProsFormSet = modelformset_factory(ProsModel, fields=('pros',), formset=BaseProsFormset)
    ConsFormSet = modelformset_factory(ConsModel, fields=('cons',),formset=BaseConsFormset)
    if request.method == 'POST':
        formset_pros = ProsFormSet(request.POST, queryset=ProsModel.objects.filter(evaluation__id=eval_name.id))
        formset_cons = ConsFormSet(request.POST, queryset=ConsModel.objects.filter(evaluation__id=eval_name.id))
        if formset_cons.is_valid() or formset_pros.is_valid():
            instances_cons = formset_cons.save(commit=False)
            instances_pros = formset_pros.save(commit=False)
            if instances_cons:
                for instance_con in instances_cons:
                    instance_con.evaluation_id = eval_name.id
                    instance_con.save()
            elif instances_pros:
                for instance_pro in instances_pros:
                    instance_pro.evaluation_id = eval_name.id
                    instance_pro.save()
        else:
            messages.info(request, 'Cons or Pros with the same content already exits')
            return HttpResponseRedirect(reverse('more_pros_cons', args=(eval_name.id,)))
    formset_cons = ConsFormSet(queryset=ConsModel.objects.filter(evaluation__id=eval_name.id))
    formset_pros = ProsFormSet(queryset=ProsModel.objects.filter(evaluation__id=eval_name.id))
    context = {'formset_cons': formset_cons,'formset_pros':formset_pros, 'eval_name':eval_name}
    return render(request,'more_pros_cons.html',context)


def eval_pros_cons_render_pdf(request,*args,**kwargs):
    pk = kwargs.get('pk')
    evaluation = get_object_or_404(EvaluationQModel,pk=pk)
    template_path = 'render_pdf_eval.html'
    context = {'evaluation': evaluation}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if we want to download
    # response['Content-Disposition'] = 'attachment; filename="topic_idea_details.pdf"'
    # if we want just to display
    response['Content-Disposition'] = 'filename="eval_pros_cons_details.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

evaluation/templates/create_evaluation_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container" >
    <div class="row mt-3">
        <form action="{% url 'eval_form' %}" method="post">
                {% csrf_token %}
                 <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Creation of Evaluation Topic</legend>
                            {{ form | crispy }}
                    </fieldset>
                <input type="submit" value="Submit Topic">
            </form>

    </div>
</div>
{% endblock %}

evaluation/templates/eval_detail.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
    <br>
    <p class="h1">{{ eval.question | title }}</p>
    <span><a class="btn btn-secondary" href="{% url 'more_pros_cons' eval.pk %}">
                    Contribute more Pros and Cons</a></span>
    <a class="btn btn-secondary" href="{% url 'pdf_format_eval' eval.pk %}">Pdf format</a></span>
                <br><br>
  <div class="row align-items-start">
    <div class="col">
      Pros
        <ul class="list-group ">{% for pros in eval.prosmodel_set.all %}
                    <li class="list-group-item">
                        {{pros | title}}
                    </li>
                    {% endfor %}
                </ul>
    </div>
    <div class="col">
      Cons
        <ul class="list-group ">
            {% for cons in eval.consmodel_set.all %}
                    <li class="list-group-item">
                        {{cons | title}}
                    </li>
            {% endfor %}
        </ul>
    </div>
  </div>
    <br>
</div>
{% endblock %}

evaluation/templates/eval_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <br>
    {% for eval in evals %}
    <a class="h1 list-group list-group-item-info" href="{% url 'eval_detail' eval.pk %}">
                    {{eval | title}}</a>
  <div class="row align-items-start">
    <div class="col">
      Pros
        <ul class="list-group ">{% for pros in eval.prosmodel_set.all %}
                    <li class="list-group-item">
                        {{pros | title}}
                    </li>
                    {% endfor %}
                </ul>
    </div>
    <div class="col">
      Cons
        <ul class="list-group ">
            {% for cons in eval.consmodel_set.all %}
                    <li class="list-group-item">
                        {{cons | title}}
                    </li>
            {% endfor %}
        </ul>
    </div>
  </div>
    <br>
      {% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            <a class="btn btn-info mb-4" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>
</div>

{% endblock %}

evaluation/templates/more_pros_cons.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if flag %}
    <h2 class="text-danger" >Please enter meaning full words</h2>
{% endif %}
{% if messages %}
    {% for message in messages %}
        <h3 class="text-info">{{ message }}</h3>
    {% endfor %}
{% endif %}

<div class="container">
    <legend class="border-bottom mb-4">
                    Evaluation for topic "{{ eval_name | capfirst }}"
    </legend>
  <div class="row">
    <div class="col">
      <form action="#" method="post">
            {{ formset.management_data }}
            {% csrf_token %}
            <fieldset class="form-group">
                    {{ formset_pros | crispy }}
            </fieldset>
            <input type="submit" value="Submit and Add more Pros"/>
        </form>
    </div>
    <div class="col">
      <form action="#" method="post">
            {{ formset.management_data }}
            {% csrf_token %}
            <fieldset class="form-group">
                    {{ formset_cons | crispy }}
            </fieldset>
            <input type="submit" value="Submit and Add more Cons"/>
        </form>
    </div>
  </div>
</div>
<br>
<br>
<a class="btn btn-secondary" href="{% url 'eval_list' %}" role="button">Go to Evaluation's</a>
<a class="btn btn-secondary" href="{% url 'pdf_format_eval' eval_name.pk %}">Pdf format</a></span>

{% endblock %}

evaluation/templates/render_pdf_eval.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pdf</title>
</head>
<body>
<h1><center>{{ evaluation | title }}</center></h1>
    <hr><hr>
  <div>
    <div>
      <h2>Pros</h2>
        <ul class="list-group ">{% for pros in evaluation.prosmodel_set.all %}
                    <li class="list-group-item">
                        {{pros | title}}
                    </li>
                    {% endfor %}
                </ul>
    </div>
    <div>
      <h2>Cons</h2>
        <ul class="list-group ">
            {% for cons in evaluation.consmodel_set.all %}
                    <li class="list-group-item">
                        {{cons | title}}
                    </li>
            {% endfor %}
        </ul>
    </div>
  </div>
    <br>
</div>
</body>
</html>

evaluation/templates/search_eval.html
{% extends 'base.html' %}
{% block content%}
    <br>
    <div class="input-group container justify-content-center">
        <form class="form-inline" action="{% url 'search_eval' %}" method="GET">
            <input name="q" class="form-control mr-sm-2" type="text" placeholder="Evaluation Topic's" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="search">Search</button>
        </form>
    </div>
<br>
<div class="container">
    {% if pros or cons  %}
        <h5><B>Search Results: {{ eval_name | title }}</B></h5>
            <div class="row align-items-start">
                <div class="col">
                Pros
                    <ul class="list-group ">
                        {% for pro in pros  %}
                            <li class="list-group-item">
                                {{ pro.pros | capfirst}}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col">
                Cons
                    <ul class="list-group ">
                        {% for con in cons  %}
                            <li class="list-group-item">
                               {{ con.cons | capfirst}}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
    {% elif start_flag %}
            <h4>Sorry no results found</h4>
    {% endif %}
</div>
{% endblock %}